Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using EntityFrameworkCore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EntityFrameworkCore.Controllers
{
    public class TeacherController : Controller
    {
        private readonly DataContext _context;
        private readonly ILogger<StudentController> _logger;

        public TeacherController(DataContext context, ILogger<StudentController> logger)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await  _context.Teachers.ToListAsync());
        }

        
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Add(Teacher teacher)
        {
            _context.Teachers.Add(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

                public async Task<IActionResult> Edit(int? id)
        {
            if(id == null) return NotFound();

            // var student = await _context.Students.FindAsync(id);
            var teacher = await _context
                                .Teachers
                                .FirstOrDefaultAsync(s => s.Id == id);
            if(teacher == null) return NotFound();

            return View(teacher);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Teacher model)
        {
            if(id != model.Id) return NotFound();

            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Teachers.Any(s => s.Id == model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Teacher/Create.cshtml
@model Teacher
<h2>Add Teacher</h2>
<hr>
<form asp-controller="Teacher" asp-action="Add" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="SurName" class="form-label">Surname</label>
        <input asp-for="SurName" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="AugurationDate" class="form-label">Auguration Date</label>
        <input asp-for="AugurationDate" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Views/Teacher/Edit.cshtml
@model Teacher
<h2>Teacher Update</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Teacher" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="SurName" class="form-label">SurName</label>
                <input asp-for="SurName" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="AugurationDate" class="form-label">AugurationDate</label>
                <input asp-for="AugurationDate" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

Views/Teacher/Index.cshtml
@model IEnumerable<Teacher>

<h2>Teachers</h2>
<a class="btn btn-primary" asp-area="" asp-controller="Teacher" asp-action="Create">Add Teacher</a>
<hr>
<table class="table table-bordered">
    <thead> 
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Name)</th>
            <th>@Html.DisplayNameFor(m => m.SurName)</th>
            <th>@Html.DisplayNameFor(m => m.AugurationDate)</th>
            <th style="width: 150px;"></th>
        </tr>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Id)</td>
                    <td>@Html.DisplayFor(m => item.Name)</td>
                    <td>@Html.DisplayFor(m => item.SurName)</td>
                    <td>@Html.DisplayFor(m => item.AugurationDate)</td>
                    <td>
                        <a asp-controller="Teacher" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Edit</a>
                        <a asp-controller="Teacher" asp-action="Delete" asp-route-id="@item.Id"  class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            }

        </tbody>
    </thead>
</table>