Controllers/CourseRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using EntityFrameworkCore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EntityFrameworkCore.Controllers
{
    public class CourseRegistrationController : Controller
    {
        private readonly ILogger<CourseRegistrationController> _logger;
        private readonly DataContext _context;

        public CourseRegistrationController(DataContext context, ILogger<CourseRegistrationController> logger)
        {
            _logger = logger;
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var courseRegistrations = await _context
                                        .CourseRegistrations
                                        .Include(x => x.Student)
                                        .Include(x => x.Course)
                                        .ToListAsync();
            return View(courseRegistrations);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.allStudents = new SelectList(await _context.Students.ToListAsync(), "Id", "NameSurname");
            ViewBag.allCourses = new SelectList(await _context.Courses.ToListAsync(), "Id", "Title");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCourse(CourseRegistration courseRegistration)
        {
            courseRegistration.RegisterDate = DateTime.Now;
           _context.CourseRegistrations.Add(courseRegistration);
           await _context.SaveChangesAsync();
           return RedirectToAction("Index");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/CourseRegistration/Create.cshtml
@model CourseRegistration

<h2>Add Course Register</h2>
<hr>
<form asp-controller="CourseRegistration" asp-action="AddCourse" method="post">
    <div class="mb-3">
        <label asp-for="StudentId" class="form-label">Öğrenci</label>
        <select asp-for="StudentId" asp-items="ViewBag.allStudents" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="CourseId" class="form-label">Kurs</label>
        <select asp-for="CourseId" asp-items="ViewBag.allCourses" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>

    <button type="submit" class="btn btn-secondary">Save</button>

</form>

Views/CourseRegistration/Index.cshtml
@model IEnumerable<CourseRegistration>

<h2>Student List</h2>
<a class="btn btn-primary" asp-area="" asp-controller="CourseRegistration" asp-action="Create">Add CourseRegistration</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Student.Name)</th>
            <th>@Html.DisplayNameFor(m => m.Course.Title)
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.DisplayFor(modelItem => item.Student.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Course.Title)</td>
            </tr>
        }
    </tbody>

</table>