Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EntityFrameworkCore.Data
{
    public class StudentController : Controller
    {
        private readonly DataContext _context;
        private readonly ILogger<StudentController> _logger;

        public StudentController(DataContext context, ILogger<StudentController> logger)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Add(Student student)
        {
            _context.Students.Add(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Index()
        {
            return View(await  _context.Students.ToListAsync());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null) return NotFound();

            // var student = await _context.Students.FindAsync(id);
            var student = await _context
                                .Students
                                .Include(s => s.CourseRegistrations)
                                .ThenInclude(s => s.Course)
                                .FirstOrDefaultAsync(s => s.Id == id);
            if(student == null) return NotFound();

            return View(student);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Student model)
        {
            if(id != model.Id) return NotFound();

            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Students.Any(s => s.Id == model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null) return NotFound();

            var student = await _context.Students.FirstOrDefaultAsync(s => s.Id == id);
            if(student == null) return NotFound();

            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var student = await _context.Students.FindAsync(id);
            if(student == null) return NotFound();

            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

    }
}

Views/Student/Create.cshtml
@model Student
<h2>Add Student</h2>
<hr>
<form asp-controller="Student" asp-action="Add" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Surname" class="form-label">Surname</label>
        <input asp-for="Surname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Views/Student/Delete.cshtml
@model Student

<p>
    <b>@Model.Name @Model.Surname isimli öğrenciyi silmek istiyor musunuz?</b>

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.Id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

Views/Student/Edit.cshtml
@model Student
<h2>Student Update</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Student" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Surname" class="form-label">Surname</label>
                <input asp-for="Surname" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Courses</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.CourseRegistrations)
            {
                <li>@item.Course.Title</li>
            }
        </ul>
    </div>
</div>

Views/Student/Index.cshtml
@model IEnumerable<Student>

<h2>Students</h2>
<a class="btn btn-primary" asp-area="" asp-controller="Student" asp-action="Create">Add Student</a>
<hr>
<table class="table table-bordered">
    <thead> 
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Name)</th>
            <th>@Html.DisplayNameFor(m => m.Surname)</th>
            <th style="width: 150px;"></th>
        </tr>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Id)</td>
                    <td>@Html.DisplayFor(m => item.Name)</td>
                    <td>@Html.DisplayFor(m => item.Surname)</td>
                    <td>
                        <a asp-controller="Student" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Edit</a>
                        <a asp-controller="Student" asp-action="Delete" asp-route-id="@item.Id"  class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            }

        </tbody>
    </thead>
</table>