Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EntityFrameworkCore.Data
{
    public class CourseController : Controller
    {
        private readonly ILogger<CourseController> _logger;
        private readonly DataContext _context;

        public CourseController(DataContext context, ILogger<CourseController> logger)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await  _context
                                .Courses
                                .Include(c => c.Teacher) 
                                .ToListAsync());
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Teachers = new SelectList(await _context.Teachers.ToListAsync(), "Id", "NameSurname");
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null) return NotFound();

            var course = await _context
                                .Courses
                                .Include(c => c.CourseRegistrations)
                                .ThenInclude(c => c.Student)
                                .Select( c => new CourseDTO
                                { 
                                    Id = c.Id,
                                    Title = c.Title,
                                    TeacherId = c.TeacherId,
                                    CourseRegistrations = c.CourseRegistrations
                                }
                                )
                                .FirstOrDefaultAsync(c => c.Id == id);
            if(course == null) return NotFound();
            
            ViewBag.Teachers = new SelectList(await _context.Teachers.ToListAsync(), "Id", "NameSurname");

            return View(course);
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CourseDTO model)
        {
            if(id != model.Id) return NotFound();

            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(new Course() { Id = model.Id, Title = model.Title, TeacherId = model.TeacherId });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException)
                {
                    if(!_context.Courses.Any(s => s.Id == model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.Teachers = new SelectList(await _context.Teachers.ToListAsync(), "Id", "NameSurname");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Course course)
        {
            _context.Courses.Add(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

           [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null) return NotFound();

            var course = await _context.Courses.FirstOrDefaultAsync(c => c.Id == id);
            if(course == null) return NotFound();

            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if(course == null) return NotFound();

            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Course/Create.cshtml
@model Course
<h2>Add Course</h2>
<hr>
<form asp-controller="Course" asp-action="Add" method="post">
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="TeacherId" class="form-label">Teacher</label>
        <select asp-for="TeacherId" class="form-select" asp-items="ViewBag.Teachers">
            <option value="">Select</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

Views/Course/Delete.cshtml
@model Course

<p>
    <b>@Model.Title kursunu silmek istiyor musunuz?</b>

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.Id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

Views/Course/Edit.cshtml
@model CourseDTO
<h2>Edit Course</h2>
<hr>
<div class="row">
    <div class="col-8">
        <form asp-controller="Course" asp-action="Edit" method="post">
            <div asp-validation-summary="All"></div>
            <input type="hidden" asp-for="Id">
            <div class="mb-3">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="TeacherId" class="form-label">Teacher</label>
                <select asp-for="TeacherId" class="form-select" asp-items="ViewBag.Teachers">
                    <option value="">Select</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Students</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.CourseRegistrations)
            {
                <li>@item.Student.NameSurname</li>
            }
        </ul>
    </div>
</div>

Views/Course/Index.cshtml
@model IEnumerable<Course>

<h2>Courses</h2>
<a class="btn btn-primary" asp-area="" asp-controller="Course" asp-action="Create">Add Course</a>
<hr>
<table class="table table-bordered">
    <thead> 
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Title)</th>
            <th>@Html.DisplayNameFor(m => m.Teacher.NameSurname)</th>
            <th style="width: 150px;"></th>
        </tr>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Id)</td>
                    <td>@Html.DisplayFor(m => item.Title)</td>
                    <td>@Html.DisplayFor(m => item.Teacher.NameSurname)</td>
                    <td>
                        <a asp-controller="Course" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Edit</a>
                        <a asp-controller="Course" asp-action="Delete" asp-route-id="@item.Id"  class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            }

        </tbody>
    </thead>
</table>